### ISSUE TITLE
How to use variables in scripts

### ISSUE THREAD

**Issue by WarDrake** [PiotrMachowski/Home-Assistant-custom-components-Saver#1]
The documentation explains how to set a variable, and it works when you check the state of the saver entity in the developer tools, but how do you use that variable in a script?

I don't see anything in the code that returns said variable.

**Comment by PiotrMachowski** [comment]
There are 2 ways to do it:
* using `saver.execute` service, as described [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver#execute-script)
* using `saver.saver` entity, as described [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver#using-in-templates)
