### ISSUE TITLE
Restore whole entity

### ISSUE THREAD

**Issue by SeLLeRoNe** [PiotrMachowski/Home-Assistant-custom-components-Saver#2]
Hi there,

Thanks for this integration, it seems quite interesting but I believe it is missing one little feature (unless I didn't understand the docs).

Would be possible to have a single command to restore a saved entity completely?
The goal would be, for example, to store a light state, change it (ex. alarm triggered) and restore it exactly as it was but without having to specify every specific attribute, so basically the goal would be calling:

```
service: saver.restore_state
data:
  entity_id: cover.living_room
```

And automatically restore the entity state and all the attributes ast they were.

Would this be possible? If so it would make the use way easier :)

Thanks
Andrea

**Comment by PiotrMachowski** [comment]
Hi,
I''m afraid it's not possible with saver, but you can do it using HA itself: [scene.create](https://www.home-assistant.io/integrations/scene#creating-scenes-on-the-fly)

**Comment by SeLLeRoNe** [comment]
Oh I actually missed that on scene you can get the current state and store it!

Thank you very much! :)
