### ISSUE TITLE
Using "saver" as a workaround to generate persistent "on the fly" scenes.

### ISSUE THREAD

**Issue by Montreal666** [PiotrMachowski/Home-Assistant-custom-components-Saver#20]
Hi, wondering if  "saver" could be used as a workaround to generate persistent "on the fly" scenes?

See more context here:

https://community.home-assistant.io/t/wth-is-there-no-service-to-update-the-values-stored-in-a-scene/477999

Maybe I'm oversimplifying this but it seems all that's missing is a way to have multiple "saver" variables/names (saver1, saver2, etc.) and hopefully make them persistent.

Let me know if this is feasible or open to your suggestions for workarounds to make scene.create persistent.

Thanks in advance.

**Comment by PiotrMachowski** [comment]
Yes, you can use [Save state](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver#save-state) functionality, but at this moment restoring the state is problematic. You would have to use attributes of`saver.saver` entity instead of `saver.restore_state` service

**Comment by Montreal666** [comment]
Thanks for the feedback, 
are saver.saver attributes persistent upon HA restart?
Also this would be limited to a single set of attributes per entity right?
Will see if I can figure out a way to do this, thanks!

**Comment by PiotrMachowski** [comment]
> are saver.saver attributes persistent upon HA restart?

Yes, `saver.saver` entity should be fully restored.

> Also this would be limited to a single set of attributes per entity right?

Yes, you are correct, saving the same entity one more time will overwrite previous state

**Comment by PiotrMachowski** [comment]
It is possible to achieve it using saver, I'm not sure what script do you mean

**Comment by Montreal666** [comment]
Ok thx, new to HA so I still have to digest some of the basics. will give it a shot and see how it goes. 

My previous automation platform allowed external scripts (VB) to interact with the core components so you could generally work around some of the limitations with very little programming skills.

**Comment by PiotrMachowski** [comment]
Good luck!
