### ISSUE TITLE
Not working, for some reason

### ISSUE THREAD

**Issue by gusarov** [PiotrMachowski/Home-Assistant-custom-components-Saver#27]
Not sure why, but it is not working at the moment (I'm on today's latest builds on Home Assistant OS, updating all components every day).

Installed via HACS, config.yaml "saver:" is there, integration is installed, service is available, nothing special in the logs related. Trying both with variables and entities:
![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver/assets/1462777/e43cfd57-b765-4c2b-bc2a-dcdd0f0854be)

But template engine is always "None"

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver/assets/1462777/784be0dc-4043-4fb8-b1e3-baf94284a2e7)

same with the automation where I'm trying to apply it. Is there anything I'm missing?

**Comment by PiotrMachowski** [comment]
Can you show attributes of `saver.saver` entity?

**Comment by gusarov** [comment]
> Can you show attributes of `saver.saver` entity?

hmm, interesting, somehow I got saver.saver_2 instead:

![image](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Saver/assets/1462777/2d5368f5-e841-4395-ac36-2817b2c70001)

**Comment by PiotrMachowski** [comment]
Huh, that's interesting. You can try to remove it, restart HA and then add again. Have you added it using UI or yaml?

**Comment by gusarov** [comment]
I can't remove because they are marked as read-only. I've added both UI and yaml 🤣am I supposed to do only one of those? Ok, I'll try to remove yaml, if will not help, will remove both, restart and add only integration on UI...

**Comment by PiotrMachowski** [comment]
> I can't remove because they are marked as read-only.

Remove the integration, not entity

Yes, you should use only one of configuration methods ;)

**Comment by gusarov** [comment]
Now it works! Thank you! 
Somehow I've interpreted main page that I'm supposed to add integration, then add yaml 🤷‍♂️ not sure, might worth to add some comment there that either this or that.
Anyway, will continue complicate my automations with this new thing, thanks :)

**Comment by PiotrMachowski** [comment]
Great!
