### ISSUE TITLE
wled effect

### ISSUE THREAD

**Issue by pafftis** [PiotrMachowski/Home-Assistant-custom-components-Saver#6]
please tell me the script, there is a wled tape. I want to save its effect state, change the effect, and then return the effect back

alias: test
sequence:

service: saver.save_state
data:
entity_id: light.wled
delay: ‘00:00:05’
service: wled.effect
data:
entity_id: light.wled
effect: police
delay: ‘00:00:05’
service: saver.restore_state
data:
entity_id: light.wled
entity_id: saver.saver
mode: single

All wled seeting:

min_mireds: 153 
max_mireds: 500 
effect_list: Android, Blink, Blink Rainbow, Bouncing Balls, Bpm, Breathe, Candle, Candle Multi, Chase, Chase Flash, Chase Flash Rnd, Chase Rainbow, Chase Random, Chunchun, Circus, Colorful, Colorloop, Colortwinkles, Colorwaves, Dancing Shadows, Dissolve, Dissolve Rnd, Drip, Dynamic, Fade, Fill Noise, Fire 2012, Fire Flicker, Fireworks, Fireworks 1D, Fireworks Starburst, Flow, Glitter, Gradient, Halloween, Halloween Eyes, Heartbeat, ICU, Juggle, Lake, Lighthouse, Lightning, Loading, Merry Christmas, Meteor, Meteor Smooth, Multi Comet, Noise 1, Noise 2, Noise 3, Noise 4, Noise Pal, Oscillate, Pacifica, Palette, Percent, Phased, Phased Noise, Plasma, Police, Police All, Popcorn, Pride 2015, Railway, Rain, Rainbow, Rainbow Runner, Random Colors, Red & Blue, Ripple, Ripple Rainbow, Running, Running 2, Saw, Scan, Scan Dual, Scanner, Scanner Dual, Sine, Sinelon, Sinelon Dual, Sinelon Rainbow, Solid, Solid Glitter, Solid Pattern, Solid Pattern Tri, Sparkle, Sparkle Dark, Sparkle+, Spots, Spots Fade, Stream, Stream 2, Strobe, Strobe Mega, Strobe Rainbow, Sunrise, Sweep, Sweep Random, Theater, Theater Rainbow, Traffic Light, Tri Chase, Tri Fade, Tri Wipe, Twinkle, Twinklecat, Twinklefox, Twinkleup, Two Areas, Two Dots, Washing Machine, Wipe, Wipe Random 
brightness: 255 
hs_color: 37.412, 100 
rgb_color: 255, 159, 0 
xy_color: 0.57, 0.41 
effect: Solid 
intensity: 128 
palette: Default 
playlist: null 
preset: null 
reverse: false 
speed: 128 
friendly_name: WLED
icon: mdi:led-strip-variant 
supported_features: 55

**Comment by PiotrMachowski** [comment]
It's not so simple with a saver, you will get a better result by using [scene snapshot])https://www.home-assistant.io/integrations/scene/#creating-scenes-on-the-fly)

**Comment by pafftis** [comment]
> It's not so simple with a saver, you will get a better result by using [scene snapshot])https://www.home-assistant.io/integrations/scene/#creating-scenes-on-the-fly)
scene snapshot, 
Saves a new scene every time, and there are many scenes

**Comment by PiotrMachowski** [comment]
If you use the same name of a scene it will be overwritten
