### ISSUE TITLE
I'm trying to save/restore all attributes of a binary_sensor, but its not working

### ISSUE THREAD

**Issue by flyize** [PiotrMachowski/Home-Assistant-custom-components-Saver#9]
Is that possible?

If it matters, my use case is this. I have a sensor that tracks the last time a pet came in/out the pet door using the attribute 'since'. HA resets that every time it restarts, and I want to preserve that timestamp.

**Comment by PiotrMachowski** [comment]
It's not possible to do it. I suggest to use e.g. `input_datetime` instead

**Comment by flyize** [comment]
Thanks for the comment!

Is the suggestion that I create an automation to map changes to 'since' to an input_datetime? So I wouldn't need Saver at all?

**Comment by PiotrMachowski** [comment]
Yup, I would suggest to set input_datetime to now() when pet comes in/out and then use this value instead of original binary sensor
